services:
  - type: web
    name: api-consumet-org # Name of the service
    env: docker
    repo: https://github.com/YaxouDBST/api.consumet.org.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3000